### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by terraboops** [hudson3-plugins/build-timeout-plugin#1]
Building the project with Maven fails.

```
[ERROR] Failed to execute goal org.eclipse.hudson.tools:maven-hpi-plugin:3.0.0-M2:hpi (default-hpi) on project build-timeout: Execution default-hpi of goal org.eclipse.hudson.tools:maven-hpi-plugin:3.0.0-M2:hpi failed: 9 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.hudson.tools:maven-hpi-plugin:3.0.0-M2:hpi (default-hpi) on project build-timeout: Execution default-hpi of goal org.eclipse.hudson.tools:maven-hpi-plugin:3.0.0-M2:hpi failed: 9
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-hpi of goal org.eclipse.hudson.tools:maven-hpi-plugin:3.0.0-M2:hpi failed: 9
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 9
    at org.codehaus.plexus.components.io.attributes.Java7FileAttributes.checkFlag(Java7FileAttributes.java:131)
    at org.codehaus.plexus.components.io.attributes.Java7FileAttributes.isWorldExecutable(Java7FileAttributes.java:161)
    at org.codehaus.plexus.components.io.attributes.Java7FileAttributes.getOctalMode(Java7FileAttributes.java:235)
    at org.codehaus.plexus.archiver.AbstractArchiver.asArchiveEntry(AbstractArchiver.java:333)
    at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:459)
    at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.addResources(AbstractZipArchiver.java:367)
    at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:312)
    at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:211)
    at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:875)
    at org.apache.maven.archiver.MavenArchiver.createArchive(MavenArchiver.java:543)
    at org.eclipse.hudson.maven.plugins.hpi.HpiMojo.performPackaging(HpiMojo.java:139)
    at org.eclipse.hudson.maven.plugins.hpi.HpiMojo.execute(HpiMojo.java:97)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 21 more
```

**Comment by bobfoster** [comment]
Fixed in repository.

**Comment by terraboops** [comment]
I don't see a commit for this? What does that mean? Which repository is it fixed in?

I am asking because I would like to contribute a fix for this bug:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=448079

**Comment by bobfoster** [comment]
Oops. Got my wires crossed and fixed build-pipeline-plugin instead. Just pushed here. Sorry.

**Comment by terraboops** [comment]
Thank you, I will endeavour to submit a fix for that issue this weekend.

**Comment by wjprakash** [comment]
Tyler, we appreciate the fix and thanks in advance.
